### ISSUE TITLE
Use Weakest Tech Console Error

### ISSUE THREAD

**Issue by MightyBirdy** [challenert/digimon_world_randomizer#101]
> [11060] Failed to execute script digimon_randomize
Traceback (most recent call last):
  File "digimon_randomize.py", line 105, in <module>
  File "digimon\handler.py", line 1715, in randomizeStarters
  File "digimon\handler.py", line 2335, in _setStarterTechs
UnboundLocalError: local variable 'lowestTierSlot' referenced before assignment

**Comment by meekrhino** [comment]
Thank you for the report!  I will try to take a look at this when I have time; I think this option has gone unused so long that it got broken at some point and I didn't notice.

**Comment by SydMontague** [comment]
This error seems to happen when the game picks a Fresh or In-Training Digimon as starter.
